name: KitPVP
author: Finn
main: me.finn.kitpvp.KitPVP
version: 0.6.0

api-version: 1.16
commands:
  kitpvp:
    aliases: [kp]

permissions:
  kitpvp.selector:
    description: Allows access directly to selector.
  kitpvp.setspawn:
    description: Allows a player to set the kitpvp spawn location.