name: KitPVP
author: Finn
main: me.finn.kitpvp.KitPVP
version: 0.6.0

api-version: 1.16
commands:
  kitpvp:
    aliases: [kp]

permissions:
  kitpvp.kits.clear:
  kitpvp.kits.create:
  kitpvp.selector:
  kitpvp.setspawn: